:doctype: article
:author: Jerod Gawne
:email: jerodgawne@gmail.com
:docdate: March 15, 2019
:revdate: {docdatetime}
:description: LibSEA - ActiveDirectory Client API
:keywords: libsea, activedirectory, api
:summary: ActiveDirectory Client API

:sectanchors:
:sectlinks:
:sectnums:
:toc:
:experimental:
:icons: font
:chkdbx: pass:normal[{startsb}&#10004;{endsb}]
:chkbx: pass:normal[{startsb}  {endsb}]
:source-highlighter: rouge

= LibSEA ActiveDirectory

{summary}

== To-Do


== Installation
NOTE: Requires an additional source be added to your projects Pipfile.

.Add Pypi Source
[source,toml]
....
[[source]]
url = "http://slgramihqaims90.info53.com:3030/simple"
verify_ssl = false
name = "pypi-sea"
....

.Install
[source,shell]
pipenv install libsea_activedirectory

== Access
Active Directory Read Permissions

=== Account
.Requires Environment Variables
* AD_USER (<domain>/<user>)
* AD_PASS
* AD_HOST (fqdn)

=== Firewall
.LAN
|===
|Port | Description | Protocol
|389 | LDAP |TCP UDP
|636 | LDAP over SSL/TLS |TCP UDP
|3268 | Global Catalog |TCP UDP
|===

.WAN
None

=== Proxy
No External (WAN) resources are accessed. Should not require proxy access.

== Location
.Production Code
This is a python package/module, it should be installed via the instructions above.

.Development Code
This is a python package/module, it should be installed via the instructions above.

.Source
https://github.info53.com/Fifth-Third/SEA_LibSEA_ActiveDirectory[GitHub]

=== Data
No data resources are accessed.


== Other Info
.Domain Info (as of 2019.04.03)
* DM0001 - Production Tier 3 user domain - Connected to myAccess +
* DM0002 - Red Forest Domain - Domain/Enterprise Admins - Connected to myAccess +
* DM0004 - PCI Domain – Will be built for future PCI application use +
* DM0005 - Privileged Access Domain - Privileged access accounts - Connected to myAccess +
* DM0006 - Legacy AD & Exchange Testing Domain +
* DM0007 - Production Tier 1 user domain - Connected to myAccess +
* DM0008 - EOL Tier 1 Domain - Server/Accounts only - Not connected to myAccess +
* DM0009 - EOL Tier 3 Domain - Server/Accounts only - Not connected to myAccess +
* TestDomain - Tier 3 Test Domain - Not connected to myAccess +
